from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
import uuid
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from database import Base


class InviteCode(Base):
    """
    Beta access invite codes.

    Generated by admins, single-use, with expiration.
    """
    __tablename__ = 'invite_codes'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    code = Column(String(50), nullable=False, unique=True, index=True)
    created_by = Column(UUID(as_uuid=True), ForeignKey('users.id'), nullable=False)
    used_by = Column(UUID(as_uuid=True), ForeignKey('users.id'), nullable=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    is_used = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def to_dict(self):
        return {
            'id': str(self.id),
            'code': self.code,
            'created_by': str(self.created_by),
            'used_by': str(self.used_by) if self.used_by else None,
            'expires_at': self.expires_at.isoformat() if self.expires_at else None,
            'is_used': self.is_used,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }

    def is_expired(self):
        from datetime import datetime, timezone
        if not self.expires_at:
            return True
        return datetime.now(timezone.utc) >= self.expires_at

    def is_valid(self):
        return not self.is_used and not self.is_expired()
